name: Build VSCode Solution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore ok-launcher.sln

    - name: Build Solution
      run: msbuild ok-launcher.sln /p:Configuration=Release

    - name: Archive Built Executable
      run: powershell Compress-Archive -Path x64/Release/ok-ww.exe -DestinationPath ok-ww.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ok-ww-executable
        path: ok-ww.zip
